### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by AlessandroMinali** [pfarnach/altvote#2]
I just came across this project off of a dead site: http://www.projectbuddy.io/

Sounded interesting. Would love to chat and see if I could contribute to any of your current projects.

**Comment by pfarnach** [comment]
Hey, thanks for getting in touch.  I've since moved forward with the project and don't need more help at the moment.  I'm going to organize some thoughts about where I want it to go and I'll let you know if this changes

**Comment by pfarnach** [comment]
Hey Alessandro, the project is moving along nicely and I could definitely use some help with design/SASS. Do you have any interest in helping out on that front?

**Comment by AlessandroMinali** [comment]
Sure, I can lend a hand. Feel free to msg me here or privately via email: `alessandro.minali AT gmail DOT com`
